"""Add asset categories and request logic updates

Revision ID: 12da4eb521db
Revises: 
Create Date: 2026-04-22 08:26:49.571219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12da4eb521db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_categories_id'), 'asset_categories', ['id'], unique=False)
    op.create_index(op.f('ix_asset_categories_name'), 'asset_categories', ['name'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('performed_by_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_performed_by_id'), 'audit_logs', ['performed_by_id'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('Pending', 'Approved', 'Rejected')", name='request_status_check'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_asset_id'), 'requests', ['asset_id'], unique=False)
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_index(op.f('ix_requests_user_id'), 'requests', ['user_id'], unique=False)
    op.add_column('assets', sa.Column('category_id', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('purchase_date', sa.Date(), nullable=True))
    op.add_column('assets', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('document_url', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('vendor', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('location', sa.String(), nullable=True))
    op.create_foreign_key(None, 'assets', 'asset_categories', ['category_id'], ['id'])
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('contact', sa.String(), nullable=True))
    op.alter_column('users', 'role_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'secondary_role_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key('fk_user_secondary_role', 'users', 'roles', ['secondary_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_secondary_role', 'users', type_='foreignkey')
    op.alter_column('users', 'secondary_role_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'contact')
    op.drop_column('users', 'department')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'location')
    op.drop_column('assets', 'vendor')
    op.drop_column('assets', 'document_url')
    op.drop_column('assets', 'image_url')
    op.drop_column('assets', 'cost')
    op.drop_column('assets', 'purchase_date')
    op.drop_column('assets', 'category_id')
    op.drop_index(op.f('ix_requests_user_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_asset_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_audit_logs_performed_by_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_asset_categories_name'), table_name='asset_categories')
    op.drop_index(op.f('ix_asset_categories_id'), table_name='asset_categories')
    op.drop_table('asset_categories')
    # ### end Alembic commands ###
